name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x] # Ensuring we are using the latest LTS version as per your updated requirements.

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Ensuring that npm is up-to-date
      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Check express in package-lock.json
        run: cat package-lock.json | grep express # See how express is defined

      - name: List installed packages
        run: npm list

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies with npm ci
        run: npm ci --verbose

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test
