name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x, 21.x]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install latest npm
        run: npm install -g npm@latest

      - name: Install dependencies
        run: npm install

      - name: Check express in package-lock.json
        run: cat package-lock.json | grep express

      - name: List installed packages
        run: npm list

      - name: Run npm ci
        run: npm ci --verbose

      - name: Build project
        run: npm run build --if-present

      - name: Run tests
        run: npm test
